services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      target: base
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "127.0.0.1:8080:5173"
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
